FROM node:20 AS build

WORKDIR /app

COPY . /app

RUN npm install

COPY . /app

RUN npm run build

FROM nginx

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
